-----BEGIN PRIVATE KEY-----
MIGTAgEAMBMGByqGSM49AgEGCCqGSM49AwEHBHkwdwIBAQQgwkIwY7oH4HjqUgev
hD+hVCHpLAG+Yhv8doHP1m9oD/CgCgYIKoZIzj0DAQehRANCAATVQdoo+7ayfp+n
cFYtwczVq2s2cB2/r+EAuYsWOJQHOIyioheTyH3dlePodm1e5suTAUWqfUHoky79
ErsQMTcx
-----END PRIVATE KEY-----